# Generated by Django 5.1.6 on 2026-03-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0002_chatlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='ip_address',
        ),
    ]
