# Generated by Django 5.1.6 on 2026-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0003_remove_ip_from_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='feedback',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
